apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-microservice-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: posts-server
          image: amitbd1508/posts-server
          ports:
            - containerPort: 4000
